Red test_end_time_overlap_create_appointment_doctor_who
Exception:

>       assert response.status_code == HTTPStatus.CONFLICT
E       assert 200 == <HTTPStatus.CONFLICT: 409>
E         +200
E         -<HTTPStatus.CONFLICT: 409>

tests\test_home.py:100: AssertionError